### ISSUE TITLE
angularWeb does not load in browser

### ISSUE THREAD

**Issue by davwards** [moonmaster9000/rpsApp#6]
angularWeb loads a blank page in browser; console shows this error:

Unhandled promise rejection Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)

**Comment by moonmaster9000** [comment]
I fixed it. Thanks!
